manageinvest/urls.py
from django.contrib import admin
from django.urls import path
from fiis.views import FiiListView, TradeDeleteView, TradesListView, NewTradeCreateView, FiiDetailView, TradeUpdateView

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", FiiListView.as_view(), name="fii_list"),
    path("trades/<int:pk>/", FiiDetailView.as_view(), name="trades"),
    path("new_trade/", NewTradeCreateView.as_view(), name="new_trade"),
    path("all_trades_list/", TradesListView.as_view(), name="all_trades_list"),
    path("trades/<int:fii_pk>/<int:pk>/update/", TradeUpdateView.as_view(), name="trade_update"),
    path("trade/<int:fii_pk>/<int:pk>/delete/", TradeDeleteView.as_view(), name="trade_delete"),

]

fiis/models.py
from django.db import models


# Create your models here.
class Fii(models.Model):
    id = models.AutoField(primary_key=True)
    name = models.CharField(max_length=10)

    def __str__(self):
        return self.name
    

class Trade(models.Model):
    TYPE_TRADE = [
        ("C", "Compra"),
        ("V", "Venda"),
        ("SUB", "Subscrição")
    ] 

    fii = models.ForeignKey(Fii, on_delete=models.CASCADE, related_name="trades")
    date = models.DateField(blank=True, null=True)
    type_trade = models.CharField(max_length=3, blank=False, null=False, choices=TYPE_TRADE, default="C",)
    amount = models.IntegerField(blank=True, null=True)
    price = models.DecimalField(max_digits=10, decimal_places=2, blank=True, null=True)
    total_trade = models.DecimalField(
        max_digits=10, decimal_places=2, blank=True, null=True)

    def save(self, *args, **kwargs):
        if self.amount and self.price:
            self.total_trade = self.amount * self.price
        else:
            self.total_trade = 0
        super().save(*args, **kwargs)
        

    def __str__(self) -> str:
        return f"compra de {self.amount} de {self.fii.name} em {self.date} no total de {self.total_trade}"
    

class FiiInventory(models.Model):
    fiis_count = models.IntegerField()
    total_amount_invested = models.FloatField()
    
    def __str__(self):
        return f"{self.fiis_count} - {self.total_amount_invested}"
        

fiis/forms.py
from django import forms
from fiis.models import Trade

class TradeForm(forms.ModelForm):
    
    class Meta:
        model = Trade
        fields = "__all__"

fiis/views.py
from django.db.models import Sum
from django.db.models.base import Model as Model
from django.db.models.query import QuerySet
from django.shortcuts import get_object_or_404, render
from django.views import View
from django.views.generic import ListView, CreateView, DetailView, DeleteView, UpdateView
from .models import Fii, Trade, FiiInventory
from .forms import TradeForm
from django.urls import reverse_lazy

# Create your views here.
#def fii_views(request):
#    fiis = Fii.objects.all()
#    
#    return render(request, "fiis.html", {"fiis": fiis})

class FiiListView(ListView):
    model = Fii
    template_name = "fiis.html"
    context_object_name = "fiis"
    


'''def trade_views(request, pk):
    fii = Fii.objects.get(id=pk)
    trades = Trade.objects.filter(fii=fii)
    
    #somando colunas
    total_amount = trades.aggregate(Sum("amount"))["amount__sum"] or 0
    total_trade = trades.aggregate(Sum("total_trade"))["total_trade__sum"] or 0
    averange = float(total_trade / total_amount)
    
    context = {
        "fii": fii,
        "trades": trades,
        "total_amount": total_amount,
        "total_trade": total_trade,
        "averange": averange    
    }
    
    return render(request, "trades.html", context)'''


class FiiDetailView(DetailView):
    model = Fii
    template_name = "fii_details.html"
    context_object_name = "fii"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        fii = self.get_object()
        trades = Trade.objects.filter(fii=fii)
        
        total_amount = trades.aggregate(Sum("amount"))["amount__sum"] or 0
        total_trade = trades.aggregate(Sum("total_trade"))["total_trade__sum"] or 0
        averange = float(total_trade / total_amount) if total_amount > 0 else 0

        context["trades"] = trades
        context["total_amount"] = total_amount
        context["total_trade"] = total_trade
        context["averange"] = averange

        return context


class NewTradeCreateView(CreateView):
    model = Trade
    form_class = TradeForm
    template_name = "new_trade.html"
    success_url = "/all_trades_list/"
    


class TradesListView(ListView):
    model = Trade
    template_name = "trade_list.html"
    context_object_name = "trades"
    
    def get_queryset(self):
        trades = super().get_queryset().order_by("-date")

        return trades
    
class TradeUpdateView(UpdateView):
    model = Trade
    form_class = TradeForm
    template_name = "update_trade.html"
    context_object_name = "trade"
    

    def get_object(self, queryset=None):
        fii_id = self.kwargs.get("fii_pk")
        trade_id = self.kwargs.get("pk")
        return get_object_or_404(Trade, pk=trade_id, fii_id=fii_id)
    
    def get_success_url(self):
        return reverse_lazy(
            "trades", kwargs={'pk': self.get_object().fii.pk})
    

class TradeDeleteView(DeleteView):
    model = Trade
    template_name = "delete_trade.html"
    context_object_name = "trade"
    
    def get_object(self):
        fii_id = self.kwargs.get("fii_pk")
        trade_id = self.kwargs.get("pk")
        #print(f"FII ID: {fii_id}, Trade ID: {trade_id}")
        return get_object_or_404(Trade, pk=trade_id, fii_id=fii_id)
    
    def get_success_url(self) -> str:
        return reverse_lazy("trades", kwargs={'pk': self.get_object().fii.pk})

fiis/templates/base.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Dashboard</title>

    <!-- Bootstrap CSS CDN -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet">
    <link href='https://unpkg.com/boxicons@2.1.4/css/boxicons.min.css' rel='stylesheet'>
</head>

<body class="bg-light">
    <!-- Barra de navegação superior -->
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark ">
        <div class="container-fluid">
            <a class="navbar-brand " href="#">Meus Investimentos</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav"
                aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNav">
                <ul class="navbar-nav ms-auto">
                    <li class="nav-item">
                        <a class="nav-link" href="#">Configurações</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="#">Perfil</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="#">Logout</a>
                    </li>
                </ul>
            </div>
        </div>
    </nav>

    <!-- Estrutura do Dashboard -->
    <div class="container-fluid" >
        <div class="row" style="height: 100%;">
            <!-- Barra lateral (Sidebar) -->
            <nav id="sidebarMenu" class=" mh-100 col-md-3 col-lg-2 d-md-block bg-dark sidebar vh-100% collapse ">
                <div class="position-sticky">
                    <ul class="nav flex-column">
                        <li class="nav-item">
                            <a class="nav-link active" aria-current="page" href="#">
                                <i class="bi bi-house"></i>
                            </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'fii_list' %}">
                                <i class="bi bi-people"></i>
                                Lista de FII
                            </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'all_trades_list' %}">
                                <i class="bi bi-bag"></i>
                                Compras
                            </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'new_trade' %}">
                                <i class="bi bi-bar-chart"></i>
                                Adicionar Transação
                            </a>
                        </li>
                    </ul>
                </div>
            </nav>

            <!-- Conteúdo Principal -->
            <main class="col-md-9 ms-sm-auto col-lg-10 px-md-4">
            <!-- Exemplo de Cards de Estatísticas -->
                <div class="row" style="margin-top: 28px;">
                    <div class="col-md-3">
                        <div class="card text-white bg-dark mb-3">
                            <div class="card-header">Total Investido</div>
                            <div class="card-body">
                                {% if inventory %}
                                <h5 class="card-title">R$ {{ inventory.total_amount_invested }}</h5>
                                {% else %}
                                <h5 class="card-title"> Sem registro </h5>
                                {% endif %}
                                <p class="card-text">Total investido em Fiis</p>
                            </div>
                        </div>
                    </div>
                    <div class="col-md-3">
                        <div class="card text-white bg-dark mb-3">
                            <div class="card-header">total de transações efetivadas</div>
                            <div class="card-body">
                                <h5 class="card-title">{{ inventory.fiis_count }}</h5>
                                <p class="card-text">ainda a ver o vai ser colocado</p>
                            </div>
                        </div>
                    </div>
                    <div class="col-md-3">
                        <div class="card text-white bg-dark mb-3">
                            <div class="card-header">Valor atual da carteira</div>
                            <div class="card-body">
                                <h5 class="card-title">R$ 0000</h5>
                                <p class="card-text">Valor atualda carteira</p>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="col-md-9">
                    <!-- Incluindo o conteúdo da página específica -->
                    {% block content %}
                    {% endblock %}
                </div>
            </main>
        </div>
    </div>
    
    <!-- Bootstrap JS CDN -->
    <script src="https://unpkg.com/boxicons@2.1.4/dist/boxicons.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js"></script>
</body>

</html>

fiis/templates/delete_trade.html
{% extends "base.html" %}

{% block content %}
    <div class="card">
        <h5 class="card-header">Deletar...</h5>
        <div class="card-body">
            <h5 class="card-title">Tem certeza que deseja deletar</h5>
            <p class="card-text">FII: {{ object.fii.name }}</p>
            <p class="card-text">Data: {{ object.date }}</p>
            <p class="card-text">Tipo: {{ object.get_type_trade_display }}</p>
            <p class="card-text">Quantidade {{ object.amount }}</p>
            <p class="card-text">Preço: R${{ ibject.price }}</p>
            <form method="post">
                {% csrf_token %}
                <button type="submit" class="btn btn-danger" data-bs-dismiss="modal">Deletar Transação</button>
                <a href="{% url 'trades' object.fii.pk %}" class="btn btn-primary">voltar</a>
            </form>
        </div>
    </div>


{% endblock %}

fiis/templates/fii_details.html
{% extends "base.html" %}

{% block content %}
<!-- Tabel de transações de cada fii -->
<div class="table-responsive rounded">
    <table class="table table-dark table-striped table-md">
        <thead>
            <tr>
                <th>Data</th>
                <th>Tipo de transação</th>
                <th>Quantidade cotas compradas</th>
                <th>Valor por cota</th>
                <th>Total pago</th>
                <th>   </th>
                <th>   </th>
            </tr>
        </thead>
        <tbody>
            {% for trade in trades %}
                <tr>
                    <td>{{ trade.date }}</td>
                    <td>{{ trade.type_trade }}</td>
                    <td>{{ trade.amount }}</td>
                    <td>R$ {{ trade.price }}</td>
                    <td>R$ {{ trade.total_trade }}</td>
                    <td><a href="{% url 'trade_update' fii.pk trade.pk %}" style="text-decoration: none;"><i class='bx bx-edit'></i></a></td>
                    <td><a href="{% url 'trade_delete' fii.pk trade.pk %}" style="text-decoration: none;"><i class='bx bx-message-square-x' ></i></a></td>
                </tr>
            {% endfor %}
        </tbody>
    </table>
    <table class="table table-dark table-striped table-md">
        <thead>
            <tr>
                <th>Total</th>
                <th>Número de cotas</th>
                <th>Total aplicado</th>
                <th>Média</th>    
            </tr>
        </thead>
        <td>TOTAL</td>
        <td>{{ total_amount }}</td>
        <td>R${{ total_trade|floatformat:2 }}</td>
        <td>R${{ averange|floatformat:2 }} </td>
    </table>
</div>


{% endblock %}

fiis/templates/fiis.html
{% extends "base.html" %}

    
{% block content %}

<!-- Tabela de Dados -->
<div class="table-responsive rounded ">
    <table class="table table-dark table-striped table-md  ">
        <thead>
            <tr>
                <th>#</th>
                <th>Nome do Fii</th>
                <th>Quantidade</th>
                <th>Preço médio</th>
                <th>Total</th>
                <th>Preço Atual</th>

                <th>Adiconar</th>
            </tr>
        </thead>
        <tbody>
            {% for fii in fiis %}
            <tr>
                <td>{{fii.id}}</td>
                <td><a href="{% url 'trades' pk=fii.pk %}">{{fii.name}}</a></td>
                <td>{{fii.total_amount}}</td>
                <td>$150.00</td>
                <td></td>
                <td>função de busca [fii.name]</td>
                <td>
                    <a href="{% url 'trades' pk=fii.pk %}"><button>+</button></a>
                </td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
</div>
{% endblock %}

fiis/templates/new_trade.html
{% extends "base.html" %}

{% block content %}
<div class="card bg-dark">
<div class="mt-4 d-flex-inline p-5 ">
    <form method="post" action="{% url 'new_trade' %}">
    {% csrf_token %}
        <div class="form-control p-3 mb-3">
            <label class="ml-3 ">FII</label>
            {{ form.fii }}
        </div>
        <div class="form-control p-3 mb-3">
            <label class="ml-3 ">Data</label>
            {{ form.date }}
        </div>
        <div class="form-control p-3 mb-3">
            <label class="ml-3 ">Tipo de transação</label>
            {{ form.type_trade }}
        </div>
        <div class="form-control p-3 mb-3">
            <label class="ml-3 ">Quantidade de cotas</label>
            {{ form.amount }}
        </div>
        <div class="form-control p-3 mb-3">
            <label class="ml-3 ">Preço</label>
            {{ form.price }}
        </div>
        <button type="submit" class="btn btn-primary " > Cadastar </button>
    </form>
</div>

{% endblock %}

fiis/templates/trade_list.html
{% extends "base.html" %}
{% block content %}
<!-- Tabela de todas Transações -->

<div class="table-responsive rounded">
    <table class="table table-dark table-striped table-md">
        <thead>
            <tr>
                <th>Nome</th>
                <th>Data</th>
                <th>Quantidade cotas compradas</th>
                <th>Valor por cota</th>
                <th>Total pago</th>
            </tr>
        </thead>
        <tbody>
            {% for trade in trades %}
                <tr>
                    <td>{{ trade.fii }}</td>
                    <td>{{ trade.date }}</td>
                    <td>{{ trade.amount }}</td>
                    <td>R$ {{ trade.price }}</td>
                    <td>R$ {{ trade.total_trade }}</td>
                </tr>
            {% endfor %}
        </tbody>
    </table>

</div>

{% endblock %}

fiis/templates/update_trade.html
{% extends "base.html" %}

{% block content %}
{% if form.errors %}
<div class="alert alert-danger">
    <ul>
        {% for field, errors in form.errors.items %}
        <li>{{ field }}: {{ errors|striptags }}</li>
        {% endfor %}
    </ul>
</div>
{% endif %}
<div class="card bg-dark">
    <div class="mt-4 d-flex-inline p-5 ">
        <form method="post" action="{% url 'trade_update' fii_pk=trade.fii.pk pk=trade.pk %}">
            {% csrf_token %}
            <h3>Editar Transação </h3>
            <div class="form-control p-3 mb-3">
                <label class="ml-3 ">Data</label>
                {{ form.fii }}
            </div>
            <div class="form-control p-3 mb-3">
                <label class="ml-3 ">Data</label>
                {{ form.date }}
            </div>
            <div class="form-control p-3 mb-3">
                <label class="ml-3 ">Tipo de transação</label>
                {{ form.type_trade }}
            </div>
            <div class="form-control p-3 mb-3">
                <label class="ml-3 ">Quantidade de cotas</label>
                {{ form.amount }}
            </div>
            <div class="form-control p-3 mb-3">
                <label class="ml-3 ">Preço</label>
                {{ form.price }}
            </div>
            <button type="submit" class="btn btn-primary "> Salvar Auterações </button>
            <a href="{% url 'all_trades_list' %}"> Cancelar  </a> 

        </form>
    </div>

    {% endblock %}